// <auto-generated />
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523103120_SeedCourseCatalog")]
    partial class SeedCourseCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseCategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseCategoryId = 1,
                            Name = "Analiz 1"
                        },
                        new
                        {
                            Id = 2,
                            CourseCategoryId = 1,
                            Name = "Analiz 2"
                        },
                        new
                        {
                            Id = 3,
                            CourseCategoryId = 1,
                            Name = "Analiz 3"
                        },
                        new
                        {
                            Id = 4,
                            CourseCategoryId = 1,
                            Name = "Analiz 4"
                        },
                        new
                        {
                            Id = 5,
                            CourseCategoryId = 1,
                            Name = "Vektör Analizi"
                        },
                        new
                        {
                            Id = 6,
                            CourseCategoryId = 1,
                            Name = "Sayısal Analiz"
                        },
                        new
                        {
                            Id = 7,
                            CourseCategoryId = 1,
                            Name = "Kompleks Analiz"
                        },
                        new
                        {
                            Id = 8,
                            CourseCategoryId = 2,
                            Name = "Lineer Cebir 1"
                        },
                        new
                        {
                            Id = 9,
                            CourseCategoryId = 2,
                            Name = "Lineer Cebir 2"
                        },
                        new
                        {
                            Id = 10,
                            CourseCategoryId = 2,
                            Name = "Soyut Cebir"
                        },
                        new
                        {
                            Id = 11,
                            CourseCategoryId = 2,
                            Name = "Sayılar Teorisi"
                        },
                        new
                        {
                            Id = 12,
                            CourseCategoryId = 3,
                            Name = "Diferansiyel Denklemler"
                        },
                        new
                        {
                            Id = 13,
                            CourseCategoryId = 3,
                            Name = "Olasılık ve İstatistik"
                        },
                        new
                        {
                            Id = 14,
                            CourseCategoryId = 3,
                            Name = "Nümerik Yöntemler"
                        });
                });

            modelBuilder.Entity("Entities.CourseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CourseCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Analiz Dersleri"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cebir Dersleri"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Uygulamalı Matematik"
                        });
                });

            modelBuilder.Entity("Entities.Course", b =>
                {
                    b.HasOne("Entities.CourseCategory", "CourseCategory")
                        .WithMany("Courses")
                        .HasForeignKey("CourseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseCategory");
                });

            modelBuilder.Entity("Entities.CourseCategory", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
